/* tslint:disable */
/* eslint-disable */
/**
 * back, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenResult
 */
export interface RefreshTokenResult {
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenResult
     */
    accessToken?: string;
}

/**
 * Check if a given object implements the RefreshTokenResult interface.
 */
export function instanceOfRefreshTokenResult(value: object): value is RefreshTokenResult {
    return true;
}

export function RefreshTokenResultFromJSON(json: any): RefreshTokenResult {
    return RefreshTokenResultFromJSONTyped(json, false);
}

export function RefreshTokenResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenResult {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
    };
}

export function RefreshTokenResultToJSON(value?: RefreshTokenResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accessToken': value['accessToken'],
    };
}

