/* tslint:disable */
/* eslint-disable */
/**
 * back, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterModel
 */
export interface RegisterModel {
    /**
     * 
     * @type {string}
     * @memberof RegisterModel
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterModel
     */
    password?: string;
}

/**
 * Check if a given object implements the RegisterModel interface.
 */
export function instanceOfRegisterModel(value: object): value is RegisterModel {
    return true;
}

export function RegisterModelFromJSON(json: any): RegisterModel {
    return RegisterModelFromJSONTyped(json, false);
}

export function RegisterModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterModel {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'] == null ? undefined : json['login'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function RegisterModelToJSON(value?: RegisterModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'login': value['login'],
        'password': value['password'],
    };
}

