/* tslint:disable */
/* eslint-disable */
/**
 * back, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferFundsModel
 */
export interface TransferFundsModel {
    /**
     * 
     * @type {number}
     * @memberof TransferFundsModel
     */
    fromAccountId?: number;
    /**
     * 
     * @type {number}
     * @memberof TransferFundsModel
     */
    toUserId?: number;
    /**
     * 
     * @type {number}
     * @memberof TransferFundsModel
     */
    toAccountId?: number;
    /**
     * 
     * @type {number}
     * @memberof TransferFundsModel
     */
    amount?: number;
}

/**
 * Check if a given object implements the TransferFundsModel interface.
 */
export function instanceOfTransferFundsModel(value: object): value is TransferFundsModel {
    return true;
}

export function TransferFundsModelFromJSON(json: any): TransferFundsModel {
    return TransferFundsModelFromJSONTyped(json, false);
}

export function TransferFundsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferFundsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'fromAccountId': json['fromAccountId'] == null ? undefined : json['fromAccountId'],
        'toUserId': json['toUserId'] == null ? undefined : json['toUserId'],
        'toAccountId': json['toAccountId'] == null ? undefined : json['toAccountId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function TransferFundsModelToJSON(value?: TransferFundsModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fromAccountId': value['fromAccountId'],
        'toUserId': value['toUserId'],
        'toAccountId': value['toAccountId'],
        'amount': value['amount'],
    };
}

